services:
  skytest:
    build: .
    command: gunicorn skytest.wsgi:application --bind 0.0.0.0:8000
    networks:
      - default-network
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default-network
    restart: always

networks:
  default-network:
    driver: bridge

volumes:
  pg_data: