services:
  skytest:
    build: .
    container_name: skytest
    env_file: .env
    ports:
      - "80:8000"
    networks:
      - default-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default-network
    restart: always

networks:
  default-network:
    driver: bridge

volumes:
  pg_data: